# Generated by Django 4.0.4 on 2022-05-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='auto_increment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='title',
            field=models.CharField(help_text='Enter an image title', max_length=100),
        ),
    ]
