# Generated by Django 4.0.4 on 2022-05-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_uploadedimage_auto_increment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any_field', models.CharField(max_length=20)),
            ],
        ),
    ]
